spring:
  activemq:
    broker-url: tcp://localhost:61616
  datasource:
    url: jdbc:h2:../database/pocDB;AUTO_SERVER\=TRUE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      indent_output: true
